import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Animals Chat",
  description: "Generated by create next app",
};

export default function RegisterSuccessLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="container" lang="en" suppressHydrationWarning>
      {children}
    </section>
  );
}
