import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Animals Chat",
  description: "Generated by create next app",
};

export default function RegisterSuccessLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="container" lang="en" suppressHydrationWarning>
      {children}
    </section>
  );
}
